### ISSUE TITLE
unit test runner in locutus fails due to TypeError caused by Depurar

### ISSUE THREAD

**Issue by kukawski** [kvz/node-depurar#7]
Running `npm run test` in locutus project fails for me with the following error

> rimraf test/languages && babel-node src/_util/cli.js writetests
> 
> path.js:7
>     throw new TypeError('Path must be a string. Received ' + inspect(path));
>     ^
> 
> TypeError: Path must be a string. Received { resolve: [Function],
>   require: [Function],
>   toString: [Function],
>   setPath: [Function],
>   path: '/Users/kukawski/Developer/locutus' }
>     at assertPath (path.js:7:11)
>     at Object.basename (path.js:1355:5)
>     at Depurar (/Users/kukawski/Developer/locutus/node_modules/depurar/lib/Depurar.js:24:26)
>     at Object.<anonymous> (util.js:7:13)
>     at Module._compile (module.js:541:32)
>     at loader (/Users/kukawski/Developer/locutus/node_modules/babel-register/lib/node.js:126:5)
>     at Object.require.extensions.(anonymous function) [as .js](/Users/kukawski/Developer/locutus/node_modules/babel-register/lib/node.js:136:7)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)

It points to this project and to the file Depurar.js:24 `parentDir = path.basename(appRoot);`

`appRoot` is expected to be string but it is an object.

**Comment by kvz** [comment]
Closed via merging #8

**Comment by kvz** [comment]
I released locutus v2.0.4 which contains the updated depurar version v0.2.2 with your fix 👍
